### ISSUE TITLE
[bug] AsyncAutoResetEvent deadlocks

### ISSUE THREAD

**Issue by jasonswearingen** [dotnet/dotNext#82] opened 2021-10-28 17:22 UTC
Run this test.   On my computer, it deadlocks after about 6 seconds

```cs
	[TestMethod]
	public async Task DotNextAsyncAutoResetEvent()
	{
		DotNext.Threading.AsyncAutoResetEvent autoResetEvent = new(false);

		var loopCount = 0;
		var setCount = 0;
		var consumedCount = 0;
		var timer =Stopwatch.StartNew();
		var lastSecondReported = 0;
		var producerTask = Task.Run(() => {

			while (true)
			{
				loopCount++;
				var didSet = autoResetEvent.Set();
				if (didSet)
				{
					setCount++;
				}

				if (timer.Elapsed > TimeSpan.FromSeconds(lastSecondReported))
				{
					var tup1 = new { loopCount };
					var tup = new { loopCount, setCount, consumedCount };
					Console.WriteLine($"t={lastSecondReported}sec:  {new { loopCount, setCount, consumedCount }}");
					lastSecondReported++;
				}

				if (timer.Elapsed > TimeSpan.FromSeconds(30))
				{
					break;
				}
			}
		});


		var consumerTask = Task.Run(async () => {

			while (true)
			{
				var success = await autoResetEvent.WaitAsync(TimeSpan.FromMilliseconds(1));
				if (success)
				{
					consumedCount++;
				}
				if (producerTask.IsCompleted)
				{
					break;
				}
			}
		});


		await producerTask;
		autoResetEvent.Set();
		await consumerTask;
	}
```

using DotNext 4.0.0-beta.8 from Nuget

**Comment by sakno** [comment] 2021-11-10 20:40
@jasonswearingen , .NEXT RC1 has been released. It uses GA version of .NET 6 so you can try tests again.

**Comment by jasonswearingen** [comment] 2021-11-11 13:39
The bug is still there.  deadlocks in same location.   tested with dotnet6.0 release

**Comment by sakno** [comment] 2021-11-11 15:53
I found the root cause:
1. Thread # 1: `ManualResetCompletionSource.CancellationRequested` is trying to enter monitor infinitely
2. Thread # 2: `ManualResetCompletionSource.OnCompleted` is trying to enter monitor infinitely
3. Thread # 3: `ManualResetCompletionSource.StopTrackingCancellation` stuck on `timeoutTracker.Dispose()` method

`timeoutTracker` is of type `CancellationTokenRegistration`. I think that `Dispose` waits for completion of cancellation callback. In the same time, cancellation callback stuck on Thread # 1. So `Dispose` is called within monitor and cancellation callback too. As a result, we observe a dead lock.

**Comment by sakno** [comment] 2021-11-11 15:56
According to [sources](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenRegistration.cs) in .NET repo, `Dispose` call is blocking while `Unregister` not.

**Comment by sakno** [comment] 2021-11-11 16:00
@jasonswearingen , many thanks for reporting this bug! The potential fix is in `develop` branch. The related commit is specified above.

**Closed** 2021-11-15 22:39 UTC
Labels: bug
